# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1351a458e07a95175ce1094940963d15f0a61e376ad6cc900cd8fccd11f774b78f26f7999c3d592f9ef2b77c26ea624e274b3cbea01e4d167f2ad7a5cd4d13

test:
  secret_key_base: 7d2e71b61c7309a1a36b8d180fbd32eaed5e64fb44fce2a7c39212836aa05c3a1d03cfd0650b53d1b549dd5b8ea420077f44770c430cb1dbfc935443e5b0a6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
